name: "ska-web-automation"

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:

      environment:
        description: "Environment"
        type: environment
        required: true
        default: dev


jobs:
  ska-web-automation:
    environment:  ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:

      - name: Generate GH app token
        uses: tibdex/github-app-token@v2.1.0
        id: app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}

      - run: echo 'GITHUB_TOKEN=${{ steps.app-token.outputs.token }}' >> $GITHUB_ENV

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Dependencies
        working-directory: ska-web-automation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          python -m playwright install chromium  

      - name: Assume AWS Management Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
          role-duration-seconds: 3600
          aws-region: eu-west-1
          role-session-name: ManagementRole

      - name: Assume AWS Account Role
        run: |
            CREDENTIALS=$(aws sts assume-role \
            --role-arn "arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/githubactions-ci" \
            --role-session-name MySessionName \
            --query "Credentials" --output json --region ${{ vars.AWS_REGION }})

            echo "AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.AccessKeyId')" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.SecretAccessKey')" >> $GITHUB_ENV
            echo "AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.SessionToken')" >> $GITHUB_ENV

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity


      - name: Run SKA Web Automation
        working-directory: ska-web-automation
        run: |
          pytest -s
        
